# Generated by Django 4.0.4 on 2022-07-01 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_historicalorder_historicalcustomer_historicalcourier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courier',
            old_name='isWorking',
            new_name='is_working',
        ),
        migrations.RenameField(
            model_name='historicalcourier',
            old_name='isWorking',
            new_name='is_working',
        ),
        migrations.RenameField(
            model_name='historicalorder',
            old_name='isDelivered',
            new_name='is_delivered',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='isDelivered',
            new_name='is_delivered',
        ),
    ]
