# Generated by Django 4.0.4 on 2022-07-09 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_isworking_courier_is_working_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalorder',
            name='courier',
        ),
        migrations.RemoveField(
            model_name='historicalorder',
            name='date',
        ),
        migrations.RemoveField(
            model_name='historicalorder',
            name='is_delivered',
        ),
        migrations.RemoveField(
            model_name='historicalorder',
            name='person',
        ),
        migrations.RemoveField(
            model_name='order',
            name='courier',
        ),
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_delivered',
        ),
        migrations.RemoveField(
            model_name='order',
            name='person',
        ),
    ]
